version: '3'

services:
  site:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: __CHANGE_ME__
      MYSQL_DATABASE: job_tracker
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
    ports:
      - "3306:3306"
networks:
  default:
    name: job_tracker
