import Head from "next/head";
import NewJobForm from "@/components/NewJobForm";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NewJobForm />
      </main>
    </>
  );
}
