import Head from "next/head";
import NewJobForm from "@/components/NewJobForm";
import JobDisplay from "@/components/JobDisplay";

export default function Home() {
  return (
    <>
      <Head>
        <title>Job Tracker</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen w-full bg-neutral-200 p-12">
        <div className="h-auto w-auto min-w-[250px] max-w-[350px] rounded-md bg-white">
          <NewJobForm />
        </div>
        <br />
        <div className="min-w-fit max-w-sm bg-white">
          <JobDisplay
            company="Test Company"
            applyDate={new Date()}
            status="accepted"
            statusDate={new Date()}
          />
        </div>
      </main>
    </>
  );
}
