import Head from "next/head";
import Link from "next/link";
import { useUser } from "@clerk/nextjs";

export default function Home() {
  const user = useUser();
  const signedIn = user.isSignedIn;
  return (
    <>
      <Head>
        <title>Job Tracker</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen w-full bg-neutral-100 p-12">
        {signedIn ? (
          <Link href={"/dashboard"}>Dashboard</Link>
        ) : (
          <Link href={"/sign-up"}>Signup</Link>
        )}
      </main>
    </>
  );
}
